### ISSUE TITLE
Add More Colors

### ISSUE THREAD

**Issue by LandonLloyd** [LandonLloyd/Game-Off-2020#1]
We need some more colors that are possible for the character to be. Add some to the JavaScript array in the `script.js` file.

**Comment by Abdelilah-Majid** [comment]
are you interested in adding someone as a dev

**Comment by LandonLloyd** [comment]
@Abdelilah-Majid You can work on this issue if you want! I don't need someone like crazy but if you wanna help contribute when things pop up that would be appreciated!

**Comment by clay099** [comment]
i'll help out on this

**Comment by LandonLloyd** [comment]
@clay099 I'll assign you! Just add some colors into the `colors` array in the `script.js` file. You don't need to do anything else with the code after that. Make sure to also read the CONTRIBUTING.md file before you contribute! :smile:

**Comment by dlloyd10** [comment]
Alright lemme start trying. I am going to contribute!

**Comment by LandonLloyd** [comment]
@dlloyd10 Thanks! Read the CONTRIBUTING.md file first

**Comment by Abdelilah-Majid** [comment]
i will try my best to contribute
