### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Abdelilah-Majid** [LandonLloyd/Game-Off-2020#5]
so i was working on a new mechanism so the bullets will go slow at first and slowly speed up;

so i have this code right here but the problem is its not accurate i mean the timing is not accurate:

		bullet.style.cssText = "animation: fly " + am_checkDead_timer * 100 + "ms linear infinite";
		am_score = score;
		let check_score = function () {
			if (score > am_score && !am_game_over) {
				am_checkDead_timer -= 2;
				bullet.style.cssText = "animation-duration: " + am_checkDead_timer * 100 + "ms";
				console.log(am_checkDead_timer, "s: " + score, "am_s: " + am_score);
				am_score = score;
			}
			setTimeout(check_score, am_checkDead_timer * 100);
		};
		setTimeout(check_score, am_checkDead_timer * 100);

at first it looks fine but while time is passing the bullet starts to glitch because the time when the func check_score start  is not the same as when the bullet start

**Comment by LandonLloyd** [comment]
So the bullet and the time don't match up?
Or is it the score and the time don't match?

**Comment by Abdelilah-Majid** [comment]
its the bullet and the time who don't match 
i think for this problem to be solved we need to move the bullet using js
i will try my best to figure it out

**Comment by Abdelilah-Majid** [comment]
oh and the score and the time don't match too;
but i think if we make the time and the bullet to sync the score will sync too

**Comment by Abdelilah-Majid** [comment]
and sorry you didn't add me to the Contributors;
if you send me the request i think it wont reach me unless you send me the request link;
